# Encoder Sentiment Pipeline

<a href="https://colab.research.google.com/github/HassanAlgoz/dl/blob/main/modules/pipelines/02-pipelines/04_text_classification.ipynb" target="_blank">
  <img src="https://raw.githubusercontent.com/HassanAlgoz/dl/main/assets/Open%20in%20Colab-F9AB00.svg" alt="Open in Colab" height="50"/>
</a>

Builds on your M2 sklearn sentiment work — here you'll use **Hugging Face pipelines** with pre-trained encoder models to classify review sentiment in a few lines of code.

**Goal:** Build sentiment analysis pipelines with encoder models and compare performance.

**Models:** [distilbert-base-uncased-finetuned-sst-2-english](https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english), [roberta-large-mnli](https://huggingface.co/FacebookAI/roberta-large-mnli), [bert-base-multilingual-uncased-sentiment](https://huggingface.co/nlptown/bert-base-multilingual-uncased-sentiment)

In [1]:
# --- Setup: Clone repo & cd into correct folder (Colab only) ---
import os
import sys
import subprocess

if "google.colab" in sys.modules:
    repo_url = "https://github.com/HassanAlgoz/dl.git"
    lab_folder = "dl/modules/pipelines/02-pipelines"

    # Only clone if the folder doesn't exist
    if not os.path.exists(lab_folder):
        subprocess.run(["git", "clone", repo_url])

    # Change working directory to the lab folder
    os.chdir(lab_folder)

## Imports

In [2]:
%pip install -qqq transformers

In [3]:
# imports
import numpy as np
import pandas as pd

# NLP pipepline import to be able to do sentiment analysis
from transformers import pipeline

from sklearn.metrics import accuracy_score, classification_report

# NLP Scenario
You are an analyst for a marketing company that just launched a new product suite of mobile devices. You have data from product reviews of the new product. We need to draft a report for our client that reports the sentiment of the reviews.

#### Product Reviews
1. "I absolutely love the TechWave X1! It has made my daily tasks so much easier and more efficient. Highly recommend it!"
2. "I'm not very impressed with the TechWave X1. It lacks some essential features and is quite slow."
3. "The TechWave X1 is fantastic! It has exceeded my expectations and has become an essential part of my daily routine."
4. "I found the TechWave X1 to be quite average. It does the job, but there's nothing particularly special about it."
5. "The TechWave X1 is terrible. It's full of glitches and crashes frequently. I regret purchasing it."
6.  "The TechWave X1 is disappointing. It doesn't live up to the hype and is missing several key functionalities."

In [4]:
# data setup
# create a list of reviews
reviews = [
    "I absolutely love the TechWave X1! It has made my daily tasks so much easier and more efficient. Highly recommend it!",
    "I'm not very impressed with the TechWave X1. It lacks some essential features and is quite slow.",
    "The TechWave X1 is fantastic! It has exceeded my expectations and has become an essential part of my daily routine.",
    "I found the TechWave X1 to be quite average. It does the job, but there's nothing particularly special about it.",
    "The TechWave X1 is terrible. It's full of glitches and crashes frequently. I regret purchasing it.",
    "The TechWave X1 is disappointing. It doesn't live up to the hype and is missing several key functionalities."
]

# Initialize the pipeline for your task: Sentiment Analysis

The default analyzer for sentiment analysis can be called with:
```python
    pipeline("sentiment-analysis")
```
This pipeline can take data at sentence, paragraph, or document level and will return a sentiment score and a label in the format of:
```python
 [{'score': 0.9991, 'label': 'POSITIVE'}]
```

The score represents the model's confidence in its prediction. A score closer to 1.0 (or 100%) indicates higher confidence in the predicted sentiment label so that learners going through it on their own can interpret the scores more easily.

Let's get started

In [ ]:
document_list = [
    "I absolutely love this new feature, it makes everything so much easier!",
    "This is the worst experience I have ever had with a software update.",
    "The weather is quite cloudy today, but it's not raining yet.",
    "I am so excited to see what happens next in this project!",
    "The performance is mediocre at best, and it needs a lot of improvement."
]

In [ ]:
from transformers import pipeline

# initialize a sentiment analysis pipeline with default model
pipe = pipeline("sentiment-analysis")
pipe(document_list)

[transformers] No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

[{'label': 'POSITIVE', 'score': 0.9998776912689209},
 {'label': 'NEGATIVE', 'score': 0.9997907280921936},
 {'label': 'NEGATIVE', 'score': 0.9733455181121826},
 {'label': 'POSITIVE', 'score': 0.9997532963752747},
 {'label': 'NEGATIVE', 'score': 0.9995112419128418}]

In [ ]:
sentiment_analyzer = pipeline(
    task="text-classification", # same as sentiment-analysis
    model="distilbert/distilbert-base-uncased-finetuned-sst-2-english"
  )

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  268MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

In [ ]:
%%time
# add your code here
sentiment_analyzer(document_list)

CPU times: user 448 ms, sys: 7.79 ms, total: 456 ms
Wall time: 458 ms

[{'label': 'POSITIVE', 'score': 0.999874472618103},
 {'label': 'NEGATIVE', 'score': 0.9997939467430115},
 {'label': 'POSITIVE', 'score': 0.9998612403869629},
 {'label': 'NEGATIVE', 'score': 0.9966417551040649},
 {'label': 'NEGATIVE', 'score': 0.9995984435081482},
 {'label': 'NEGATIVE', 'score': 0.9998151659965515}]

# Finding a suitable model

One way to find suitable models in Hugging Face is to search:
- Go to the Hugging Face home page
- Click on **Models** at the top
- On the left hand side select **Tasks**
- Select **Text Classification** lower down on the left hand side
- Then search for ‘**sentiment**’ in the search box on the right

Suitable models will appear (usually thousands), and you can sort by ‘**Most likes**’.  Model size will give you an indication of how resource intensive the model will be.

Let's use the `nlptown/bert-base-multilingual-uncased-sentiment` model as it is ranked very highly.  (If you search within the results for the `roberta-large-mnli` model, it's not there.)

Which model would you choose? It may be helpful to review the model card for each to help decide:

- [distilbert-base-uncased-finetuned-sst-2-english](https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english)
- [FacebookAI/roberta-large-mnli](https://huggingface.co/FacebookAI/roberta-large-mnli)

## Running it on the reviews dataset

Now let's use a model that is fine-tuned specifically for sentiment analysis.

1. Load our `reviews.csv` file
2. Build a sentiment pipeline that uses [nlptown/bert-base-multilingual-uncased-sentiment](https://huggingface.co/nlptown/bert-base-multilingual-uncased-sentiment)
3. Compare the actual 5 star reviews with the **predicted reviews (1-5 stars)** in the data set

In [11]:
# read in data (../data/reviews.csv) to a pandas DataFrame
df = pd.read_csv('../data/reviews.csv')
df.head()

,date,review,rating,product
0,2024-01-01,Absolutely love the 48MP main camera and HDR s...,5,TechWave X1
1,2024-01-01,Major disappointment. Constant heating issues ...,2,TechWave X1
2,2024-01-02,The optical stabilization and 4K video recordi...,3,TechWave X1
3,2024-01-02,Cannot recommend this device. Poor RAM managem...,1,TechWave X1
4,2024-01-03,Outstanding performance for daily tasks. The 5...,5,TechWave X1

In [12]:
# initialize a sentiment analysis pipeline with your model
pipe = pipeline(
  task="sentiment-analysis",
  model="nlptown/bert-base-multilingual-uncased-sentiment"
)

config.json:   0%|          | 0.00/953 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  669MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/39.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/872k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [14]:
inputs = df["review"].tolist()
inputs[:5]

['Absolutely love the 48MP main camera and HDR support. The processing speed is outstanding. Color accuracy on the display is fantastic.',
 'Major disappointment. Constant heating issues during gaming and camera bump is awkwardly large. Battery drains too quickly under load.',
 'The optical stabilization and 4K video recording are impressive, but the low light performance needs improvement. Battery life is decent.',
 'Cannot recommend this device. Poor RAM management leads to frequent app crashes. The fingerprint sensor is unreliable.',
 'Outstanding performance for daily tasks. The 5G connectivity is solid and facial recognition works perfectly. Very satisfied with purchase.']

In [ ]:
%%time
# run the pipeline on the reviews column
# note: our pipeline can take a list of documents, so .tolist() may be helpful
results = pipe(inputs[:5])
results

CPU times: user 25.8 s, sys: 20.4 ms, total: 25.9 s
Wall time: 26.1 s

[{'label': '5 stars', 'score': 0.9554434418678284},
 {'label': '1 star', 'score': 0.5282196402549744},
 {'label': '3 stars', 'score': 0.6016145348548889},
 {'label': '1 star', 'score': 0.7368255853652954},
 {'label': '5 stars', 'score': 0.889898419380188},
 {'label': '4 stars', 'score': 0.5942327976226807},
 {'label': '2 stars', 'score': 0.5836725831031799},
 {'label': '5 stars', 'score': 0.8990577459335327},
 {'label': '3 stars', 'score': 0.6867391467094421},
 {'label': '5 stars', 'score': 0.8594740033149719},
 {'label': '2 stars', 'score': 0.5931228995323181},
 {'label': '5 stars', 'score': 0.8948889970779419},
 {'label': '3 stars', 'score': 0.581841230392456},
 {'label': '5 stars', 'score': 0.6241867542266846},
 {'label': '2 stars', 'score': 0.49810871481895447},
 {'label': '5 stars', 'score': 0.8058336973190308},
 {'label': '3 stars', 'score': 0.5274311304092407},
 {'label': '5 stars', 'score': 0.8041918277740479},
 {'label': '2 stars', 'score': 0.5414685010910034},
 {'label': '5 stars', 'score': 0.8816862106323242},
 {'label': '4 stars', 'score': 0.7678325176239014},
 {'label': '2 stars', 'score': 0.6615797877311707},
 {'label': '5 stars', 'score': 0.9447755217552185},
 {'label': '4 stars', 'score': 0.4264991879463196},
 {'label': '5 stars', 'score': 0.8376073837280273},
 {'label': '1 star', 'score': 0.48655256628990173},
 {'label': '5 stars', 'score': 0.45315638184547424},
 {'label': '2 stars', 'score': 0.48050084710121155},
 {'label': '5 stars', 'score': 0.6322154998779297},
 {'label': '2 stars', 'score': 0.49908459186553955},
 {'label': '5 stars', 'score': 0.7596529126167297},
 {'label': '2 stars', 'score': 0.5321889519691467},
 {'label': '5 stars', 'score': 0.6139143705368042},
 {'label': '3 stars', 'score': 0.6568500995635986},
 {'label': '5 stars', 'score': 0.833888053894043},
 {'label': '2 stars', 'score': 0.5327067971229553},
 {'label': '5 stars', 'score': 0.6952837705612183},
 {'label': '2 stars', 'score': 0.5394852757453918},
 {'label': '5 stars', 'score': 0.9161961078643799},
 {'label': '3 stars', 'score': 0.5035361051559448},
 {'label': '5 stars', 'score': 0.6181405186653137},
 {'label': '1 star', 'score': 0.7299987077713013},
 {'label': '3 stars', 'score': 0.48110663890838623},
 {'label': '5 stars', 'score': 0.8378454446792603},
 {'label': '2 stars', 'score': 0.43764054775238037},
 {'label': '5 stars', 'score': 0.8981309533119202},
 {'label': '3 stars', 'score': 0.7653588652610779},
 {'label': '5 stars', 'score': 0.7606005072593689},
 {'label': '2 stars', 'score': 0.5808961987495422},
 {'label': '5 stars', 'score': 0.8689937591552734},
 {'label': '3 stars', 'score': 0.40461602807044983},
 {'label': '5 stars', 'score': 0.8357164263725281},
 {'label': '1 star', 'score': 0.44356536865234375},
 {'label': '5 stars', 'score': 0.8641867637634277},
 {'label': '3 stars', 'score': 0.636244535446167},
 {'label': '5 stars', 'score': 0.7281068563461304},
 {'label': '2 stars', 'score': 0.46804460883140564},
 {'label': '5 stars', 'score': 0.8933045864105225},
 {'label': '3 stars', 'score': 0.5497767329216003},
 {'label': '5 stars', 'score': 0.9768200516700745},
 {'label': '5 stars', 'score': 0.6938438415527344},
 {'label': '1 star', 'score': 0.8894801139831543},
 {'label': '5 stars', 'score': 0.8988229036331177},
 {'label': '3 stars', 'score': 0.7268564105033875},
 {'label': '5 stars', 'score': 0.8221089243888855},
 {'label': '2 stars', 'score': 0.5247630476951599},
 {'label': '4 stars', 'score': 0.5171554088592529},
 {'label': '2 stars', 'score': 0.552389919757843},
 {'label': '5 stars', 'score': 0.973741888999939},
 {'label': '2 stars', 'score': 0.49271488189697266},
 {'label': '5 stars', 'score': 0.8484492301940918},
 {'label': '3 stars', 'score': 0.5169932842254639},
 {'label': '5 stars', 'score': 0.8273881673812866},
 {'label': '2 stars', 'score': 0.4322676658630371},
 {'label': '5 stars', 'score': 0.6946374177932739},
 {'label': '2 stars', 'score': 0.4195837080478668},
 {'label': '5 stars', 'score': 0.8764050006866455},
 {'label': '1 star', 'score': 0.5086521506309509},
 {'label': '3 stars', 'score': 0.503139853477478},
 {'label': '5 stars', 'score': 0.6975947022438049},
 {'label': '5 stars', 'score': 0.9880871772766113},
 {'label': '5 stars', 'score': 0.9295963644981384},
 {'label': '5 stars', 'score': 0.8975215554237366},
 {'label': '5 stars', 'score': 0.8867549896240234},
 {'label': '5 stars', 'score': 0.7904866337776184},
 {'label': '5 stars', 'score': 0.8605285882949829},
 {'label': '5 stars', 'score': 0.8557499051094055},
 {'label': '5 stars', 'score': 0.847941517829895},
 {'label': '5 stars', 'score': 0.9632079601287842},
 {'label': '5 stars', 'score': 0.8903299570083618},
 {'label': '5 stars', 'score': 0.8420509696006775},
 {'label': '5 stars', 'score': 0.8046911358833313},
 {'label': '4 stars', 'score': 0.30528828501701355},
 {'label': '5 stars', 'score': 0.863370954990387},
 {'label': '5 stars', 'score': 0.8764389753341675},
 {'label': '5 stars', 'score': 0.9160174131393433},
 {'label': '5 stars', 'score': 0.8450148701667786},
 {'label': '5 stars', 'score': 0.464974045753479},
 {'label': '5 stars', 'score': 0.9123324155807495},
 {'label': '5 stars', 'score': 0.9865744709968567},
 {'label': '5 stars', 'score': 0.8151488304138184},
 {'label': '5 stars', 'score': 0.7280924320220947},
 {'label': '5 stars', 'score': 0.8862744569778442},
 {'label': '5 stars', 'score': 0.9347042441368103},
 {'label': '5 stars', 'score': 0.8950909376144409},
 {'label': '5 stars', 'score': 0.6971980333328247},
 {'label': '5 stars', 'score': 0.8550525307655334},
 {'label': '5 stars', 'score': 0.9697237610816956},
 {'label': '5 stars', 'score': 0.9144579172134399},
 {'label': '5 stars', 'score': 0.9491013884544373},
 {'label': '5 stars', 'score': 0.8039453625679016},
 {'label': '5 stars', 'score': 0.8829379677772522},
 {'label': '5 stars', 'score': 0.888666570186615},
 {'label': '5 stars', 'score': 0.8055030703544617},
 {'label': '5 stars', 'score': 0.9265171885490417},
 {'label': '5 stars', 'score': 0.9220085740089417},
 {'label': '5 stars', 'score': 0.8224157094955444},
 {'label': '5 stars', 'score': 0.8313368558883667},
 {'label': '5 stars', 'score': 0.8756309747695923},
 {'label': '5 stars', 'score': 0.9879946112632751},
 {'label': '3 stars', 'score': 0.3381214141845703},
 {'label': '5 stars', 'score': 0.8729715347290039},
 {'label': '5 stars', 'score': 0.9309134483337402},
 {'label': '5 stars', 'score': 0.8932620882987976},
 {'label': '4 stars', 'score': 0.3768101632595062},
 {'label': '5 stars', 'score': 0.9166269898414612},
 {'label': '5 stars', 'score': 0.8168051242828369},
 {'label': '5 stars', 'score': 0.8561379313468933},
 {'label': '5 stars', 'score': 0.8000818490982056},
 {'label': '5 stars', 'score': 0.6671138405799866},
 {'label': '5 stars', 'score': 0.869300127029419},
 {'label': '5 stars', 'score': 0.4657500982284546},
 {'label': '5 stars', 'score': 0.7778592705726624},
 {'label': '5 stars', 'score': 0.9676592350006104},
 {'label': '5 stars', 'score': 0.5004976987838745},
 {'label': '5 stars', 'score': 0.870282769203186},
 {'label': '5 stars', 'score': 0.817954957485199},
 {'label': '5 stars', 'score': 0.7249883413314819},
 {'label': '5 stars', 'score': 0.9677353501319885},
 {'label': '5 stars', 'score': 0.5649757385253906},
 {'label': '5 stars', 'score': 0.6369694471359253},
 {'label': '5 stars', 'score': 0.6989204287528992},
 {'label': '5 stars', 'score': 0.9117388129234314},
 {'label': '5 stars', 'score': 0.9165393710136414},
 {'label': '5 stars', 'score': 0.536914050579071},
 {'label': '5 stars', 'score': 0.7001398801803589},
 {'label': '5 stars', 'score': 0.7188735604286194},
 {'label': '5 stars', 'score': 0.8232766389846802},
 {'label': '5 stars', 'score': 0.9044398069381714},
 {'label': '5 stars', 'score': 0.9157701134681702},
 {'label': '5 stars', 'score': 0.7684714794158936},
 {'label': '5 stars', 'score': 0.9672227501869202},
 {'label': '5 stars', 'score': 0.8203237056732178},
 {'label': '5 stars', 'score': 0.8968244194984436},
 {'label': '5 stars', 'score': 0.7144443392753601},
 {'label': '5 stars', 'score': 0.6194294095039368},
 {'label': '5 stars', 'score': 0.7493944764137268},
 {'label': '5 stars', 'score': 0.8690951466560364},
 {'label': '2 stars', 'score': 0.41163042187690735},
 {'label': '5 stars', 'score': 0.8941754102706909},
 {'label': '5 stars', 'score': 0.7756004929542542},
 {'label': '5 stars', 'score': 0.7551863789558411},
 {'label': '5 stars', 'score': 0.863582193851471},
 {'label': '5 stars', 'score': 0.9072617292404175},
 {'label': '5 stars', 'score': 0.8550103306770325},
 {'label': '5 stars', 'score': 0.8612461090087891},
 {'label': '5 stars', 'score': 0.7492933869361877},
 {'label': '5 stars', 'score': 0.722223162651062},
 {'label': '5 stars', 'score': 0.8581352829933167},
 {'label': '5 stars', 'score': 0.8339415192604065},
 {'label': '5 stars', 'score': 0.7614014744758606},
 {'label': '5 stars', 'score': 0.8270977139472961},
 {'label': '5 stars', 'score': 0.775041401386261},
 {'label': '5 stars', 'score': 0.811370849609375},
 {'label': '5 stars', 'score': 0.4742219150066376},
 {'label': '5 stars', 'score': 0.8550199866294861},
 {'label': '5 stars', 'score': 0.6548205614089966},
 {'label': '5 stars', 'score': 0.8999279141426086},
 {'label': '5 stars', 'score': 0.6595375537872314},
 {'label': '5 stars', 'score': 0.9453845620155334},
 {'label': '5 stars', 'score': 0.4987083673477173},
 {'label': '5 stars', 'score': 0.8683005571365356},
 {'label': '5 stars', 'score': 0.7566655874252319},
 {'label': '5 stars', 'score': 0.7489558458328247},
 {'label': '5 stars', 'score': 0.6707293391227722},
 {'label': '5 stars', 'score': 0.9058936834335327},
 {'label': '5 stars', 'score': 0.7143331170082092},
 {'label': '5 stars', 'score': 0.7352281808853149},
 {'label': '5 stars', 'score': 0.8479323387145996},
 {'label': '5 stars', 'score': 0.4568363428115845},
 {'label': '5 stars', 'score': 0.6529178023338318},
 {'label': '5 stars', 'score': 0.5742090344429016},
 {'label': '5 stars', 'score': 0.7589678764343262},
 {'label': '5 stars', 'score': 0.6688387393951416},
 {'label': '5 stars', 'score': 0.8708595633506775},
 {'label': '5 stars', 'score': 0.8361697793006897},
 {'label': '5 stars', 'score': 0.7382648587226868},
 {'label': '5 stars', 'score': 0.49538516998291016},
 {'label': '5 stars', 'score': 0.9308933615684509},
 {'label': '5 stars', 'score': 0.6605793833732605},
 {'label': '1 star', 'score': 0.36475053429603577},
 {'label': '5 stars', 'score': 0.682374894618988},
 {'label': '5 stars', 'score': 0.8858771324157715},
 {'label': '5 stars', 'score': 0.8559722900390625},
 {'label': '5 stars', 'score': 0.5938931703567505},
 {'label': '5 stars', 'score': 0.8817251920700073},
 {'label': '4 stars', 'score': 0.4363820552825928},
 {'label': '5 stars', 'score': 0.8289811611175537},
 {'label': '5 stars', 'score': 0.661076009273529},
 {'label': '5 stars', 'score': 0.6519832611083984},
 {'label': '5 stars', 'score': 0.7276320457458496},
 {'label': '5 stars', 'score': 0.4605773091316223},
 {'label': '3 stars', 'score': 0.27863678336143494},
 {'label': '5 stars', 'score': 0.49784353375434875},
 {'label': '5 stars', 'score': 0.7673510313034058},
 {'label': '5 stars', 'score': 0.6043716669082642},
 {'label': '5 stars', 'score': 0.5552411079406738},
 {'label': '5 stars', 'score': 0.44841399788856506},
 {'label': '5 stars', 'score': 0.8907238245010376},
 {'label': '5 stars', 'score': 0.9211680889129639}]

In [ ]:
# save your results as predicted_rating and predicted_score columns in the df
df[["predicted_rating", "predicted_score"]] = pd.DataFrame(results)
# drop the star from the predicted_star column using df["predicted_star"].apply(lambda x: int(x.split(" ")[0])) and save it back to the column
df["predicted_rating"] = df["predicted_rating"].apply(lambda x: int(x.split(" ")[0]))
df.head()

,date,review,rating,product,predicted_rating,predicted_score
0,2024-01-01,Absolutely love the 48MP main camera and HDR s...,5,TechWave X1,5,0.955443
1,2024-01-01,Major disappointment. Constant heating issues ...,2,TechWave X1,1,0.528220
2,2024-01-02,The optical stabilization and 4K video recordi...,3,TechWave X1,3,0.601615
3,2024-01-02,Cannot recommend this device. Poor RAM managem...,1,TechWave X1,1,0.736826
4,2024-01-03,Outstanding performance for daily tasks. The 5...,5,TechWave X1,5,0.889898

In [ ]:
# check similarity between the predicted rating and the actual rating column

# generate classification report
print("\nClassification Report:")
print(classification_report(df['rating'], df['predicted_rating']))

Classification Report:
              precision    recall  f1-score   support

           1       0.50      0.80      0.62         5
           2       0.84      0.80      0.82        20
           3       0.69      0.79      0.73        14
           4       0.57      0.11      0.18        37
           5       0.82      0.97      0.89       144

    accuracy                           0.80       220
   macro avg       0.68      0.69      0.65       220
weighted avg       0.77      0.80      0.75       220

In [ ]:
pd.crosstab(df['rating'], df['predicted_rating'])

predicted_rating  1   2   3  4    5
rating
1                 4   1   0  0    0
2                 3  16   1  0    0
3                 0   1  11  1    1
4                 0   1   3  4   29
5                 1   0   1  2  140

## Conclusion
1. Hugging Face Pipeline API is helpful for quickly preprocessing and analyzing data using pre-trained models
2. Select the best model for your task or use the defaults for quick prototyping
3. Use labeled data to evaluate model performance